var products = [
    {
        id: 1,
        productName: "Apple",
        productModel: "iPhone 13 (128GB) - (Product) RED",
        productImage: "https://m.media-amazon.com/images/I/71gm8v4uPBL._AC_UY218_.jpg",
        USD: 70,
        EUR: 65,
        GBP: 83,
        productPrice: 1099.99,
        productRating: 4.8,
    },
    {
        id: 2,
        productName: "Redmi",
        productModel: "A2 (Aqua Blue, 2GB RAM, 64GB Storage)",
        productImage: "https://m.media-amazon.com/images/I/81RR0TAz+5L._AC_UY218_.jpg",
        USD: 55,
        EUR: 63,
        GBP: 85,
        productPrice: 899.99,
        productRating: 4.5,
    },
    {
        id: 3,
        productName: "Samsung",
        productModel: "Galaxy M04 Dark Blue, 4GB RAM, 64GB Storage",
        USD: 54,
        EUR: 75,
        GBP: 80,
        productImage: "https://m.media-amazon.com/images/I/81xJ80yRRzL._AC_UY218_.jpg",
        productPrice: 2399.99,
        productRating: 4.7,
    },
    {
        id: 4,
        productName: "realme",
        productModel: "narzo 60X 5G（Nebula Purple 6GB,128GB Storage）",
        productImage: "https://m.media-amazon.com/images/I/818UhQ1kpdL._AC_UY218_.jpg",
        USD: 33,
        EUR: 64,
        GBP: 23,
        productPrice: 499.99,
        productRating: 4.9,
    },

    {
        id: 5,
        productName: "POCO",
        productModel: "C51 (Power Black, 6GB RAM, 128GB Storage)",
        productImage: "https://m.media-amazon.com/images/I/61NJ8pnt8FL._AC_UY218_.jpg",
        USD: 59,
        EUR: 65,
        GBP: 10,
        productPrice: 599.99,
        productRating: 4.5,
    },
    {
        id: 6,
        productName: "OnePlus",
        productModel: "Nord CE 2 5G (Bahamas Blue, 8GB RAM, 128GB Storage)",
        productImage: "https://m.media-amazon.com/images/I/61+Q6Rh3OQL._AC_UY218_.jpg",
        USD: 88,
        EUR: 76,
        GBP: 33,
        productPrice: 2499.99,
        productRating: 4.9,
    },
    {
        id:7,
        productName: "iQOO",
        productModel: "Z7s 5G by vivo (Pacific Night, 6GB RAM, 128GB Storage)",
        productImage: "https://m.media-amazon.com/images/I/51oW-QOqhaL._AC_UY218_.jpg",
        USD: 58,
        EUR: 44,
        GBP: 36,
        productPrice: 349.99,
        productRating: 4.7,
    },
    {
        id:8,
        productName: "Itel",
        productModel: "A70 Smartphone",
        productImage: "https://m.media-amazon.com/images/I/611eOgyGbLL._AC_UY218_.jpg",
        USD: 11,
        EUR: 64,
        GBP: 85,
        productPrice: 179.99,
        productRating: 4.4,
    },
    {
        id:9,
        productName: "Motorola",
        productModel: "e13 (Aurora Green, 4GB RAM 64GB Storage)",
        productImage: "https://m.media-amazon.com/images/I/51154O03lbL._AC_UY218_.jpg",
        USD: 81,
        EUR: 40,
        GBP: 35,
        productPrice: 299.99,
        productRating: 4.6,
    },
    {
        id:10,
        productName: "Apple",
        productModel: "iPhone 13 (128GB) - (Product) RED",
        productImage: "https://m.media-amazon.com/images/I/71gm8v4uPBL._AC_UY218_.jpg",
        USD: 70,
        EUR: 65,
        GBP: 83,
        productPrice: 1099.99,
        productRating: 4.8,
    },
    {
        id:11,
        productName: "Redmi",
        productModel: "A2 (Aqua Blue, 2GB RAM, 64GB Storage)",
        productImage: "https://m.media-amazon.com/images/I/81RR0TAz+5L._AC_UY218_.jpg",
        USD: 55,
        EUR: 63,
        GBP: 85,
        productPrice: 899.99,
        productRating: 4.5,
    },
    {
        id:12,
        productName: "Samsung",
        productModel: "Galaxy M04 Dark Blue, 4GB RAM, 64GB Storage",
        USD: 54,
        EUR: 75,
        GBP: 80,
        productImage: "https://m.media-amazon.com/images/I/81xJ80yRRzL._AC_UY218_.jpg",
        productPrice: 2399.99,
        productRating: 4.7,
    },
    {
        id:13,
        productName: "realme",
        productModel: "narzo 60X 5G（Nebula Purple 6GB,128GB Storage）",
        productImage: "https://m.media-amazon.com/images/I/818UhQ1kpdL._AC_UY218_.jpg",
        USD: 33,
        EUR: 64,
        GBP: 23,
        productPrice: 499.99,
        productRating: 4.9,
    }
];

//product 
module.exports.products = (req, res) => {
    res.json({
        status: 200,
        message: "success",
        data: products
    });
};